Add friends likes
A-Kireev/java-filmorate pull request #2
Opened 2022-08-20 18:17 UTC by A-Kireev

2022-08-21 07:25 UTC, Frilock requested changes
Добрый день, с задачей справились, но написал пару комментариев, где на мой взгляд, можно лучше. Кроме того, не вижу, чтобы были протестированы новые, созданные Вами, методы.

2022-08-21 07:25 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +public class ErrorResponse {
Я так понимаю, вы создаете данный класс по примеру из курса, но там в классе 2 поля, а тут одно, в чем смысл создания данного класса с 1 полем? Почему просто строчку не использовать?

2022-08-21 07:25 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +  public FilmController(FilmStorage filmStorage, FilmService filmService) {
Можете повесить аннотацию RequairedArgsConstructor, чтобы явно конструктор не создавать

2022-08-21 07:25 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +  private Set<Integer> likes;
Вообще для идентификаторов лучше Long использовать, чтобы потом вдруг переполнения не было

2022-08-21 07:25 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    if (filmStorage.getFilmById(filmId).getLikes().contains(userId)) {
2 раза делайте filmStorage.getFilmById(filmId).getLikes() - лучше сделайте эту операцию перед циклом, а затем используйте результат, так будет более оптимально

2022-08-21 07:25 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +  public void addLike(@PathVariable int id, @PathVariable int userId) {
Не вижу чтобы были протестированы новые методы

2022-08-22 19:03 UTC, Frilock approved these changes
Работу принял, но мне не понравилось одно место. О нем написал развернутый комментарий, учтите его при выполнении следующей работы. Кроме того, как вариант, для storage классов можно было создать некий абстрактный класс и вынести туда логику, поскольку она довольно похожа.

2022-08-22 19:03 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmsHandlerTest.java
> +  void deleteLikeFromFilmTest() {
Иногда когда описание теста сложно уместить в его названии, можно воспользоваться аннотацией DisplayName("Кратко что делает тест")

2022-08-22 20:09 UTC, A-Kireev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +  private final FilmStorage filmStorage;
Да, учту в следющей работе, спасибо)

2022-08-28 19:56 UTC, merged